### ISSUE TITLE
Unable to parse IP addresses in hostname part of user info

### ISSUE THREAD

**Issue by glguy** [kallisti-dev/irc-bytestring#2]
The library doesn't handle IP addresses as the host in a message prefix.

Quote from the RFC

```
 servername =  hostname
  host       =  hostname / hostaddr
  hostname   =  shortname *( "." shortname )
  shortname  =  ( letter / digit ) *( letter / digit / "-" )
                *( letter / digit )
                  ; as specified in RFC 1123 [HNAME]
  hostaddr   =  ip4addr / ip6addr
  ip4addr    =  1*3digit "." 1*3digit "." 1*3digit "." 1*3digit
  ip6addr    =  1*hexdigit 7( ":" 1*hexdigit )
  ip6addr    =/ "0:0:0:0:0:" ( "0" / "FFFF" ) ":" ip4addr
```

Example message that can't be parsed.

```
:demo!demo@10.0.0.18 JOIN :#test
```

**Comment by kallisti-dev** [comment]
Should be pretty easy to fix. I'll look into it. In general I think this parser should have more options in terms of customizing what is allowed and disallowed, but I am not an expert on IRC server/client behavior, so I don't know exactly what options would be relevant.

**Comment by glguy** [comment]
An additional parsing error on nicknames, they don't have to start with an alpha:

```
nickname   =  ( letter / special ) *8( letter / digit / special / "-" )
```

I noticed this user quit recently (IP address removed)

```
_________!~textual@0.0.0.0
```

Additionally (at least on Freenode and any other server that uses inspircd) a nickname can start with a digit. This occurs after a netsplit. When nicks collide, one of the nicks is reassigned to its network ID, which is always prefixed with a number as a matter of namespacing!

**Comment by glguy** [comment]
(Sorry for the flood, but it's all on the same topic)

isSpecial is missing the pipe character `|`

```
  special    =  %x5B-60 / %x7B-7D
                   ; "[", "]", "\", "`", "_", "^", "{", "|", "}"
```

**Comment by kallisti-dev** [comment]
I was using https://tools.ietf.org/html/rfc1459 as a guideline for parsing criteria.

```
<message>  ::= [':' <prefix> <SPACE> ] <command> <params> <crlf>
<prefix>   ::= <servername> | <nick> [ '!' <user> ] [ '@' <host> ]
<command>  ::= <letter> { <letter> } | <number> <number> <number>
<SPACE>    ::= ' ' { ' ' }
<params>   ::= <SPACE> [ ':' <trailing> | <middle> <params> ]

<middle>   ::= <Any *non-empty* sequence of octets not including SPACE
               or NUL or CR or LF, the first of which may not be ':'>
<trailing> ::= <Any, possibly *empty*, sequence of octets not including
                 NUL or CR or LF>

<crlf>     ::= CR LF

<target>     ::= <to> [ "," <target> ]
<to>         ::= <channel> | <user> '@' <servername> | <nick> | <mask>
<channel>    ::= ('#' | '&') <chstring>
<servername> ::= <host>
<host>       ::= see RFC 952 [DNS:4] for details on allowed hostnames
<nick>       ::= <letter> { <letter> | <number> | <special> }
<mask>       ::= ('#' | '$') <chstring>
<chstring>   ::= <any 8bit code except SPACE, BELL, NUL, CR, LF and
                 comma (',')>
```
Which RFC are you referring to? Perhaps this one is obsolete now.
    
Regardless, it would appear the RFC isn't followed very well, so there's definitely a strong case to be made for relaxing the parser. I think towards this goal, it would be a good idea to set up a record that allows you to specify valid tokens for different segments of a message. 

I've consider a number of different formats for this record, and I think the best choice is to simply allow attoparsec parsers to be used to describe the tokens.

```
    data IRCParseConfig = IRCParseConfig {
        nickParser :: Parser ByteString,
        userParser :: Parser ByteString,
        ...
    }
```

This is nice in a number of ways. You can easily enforce the RFC definitions this way, and you can provide an extensive library of parsers to compose together and plug-in. The only issues I can see is that some user-defined parsers may become difficult to debug, but that's something that can be addressed later and isn't a major concern to me.

**Comment by kallisti-dev** [comment]
Do you have a short example log from an inspircd server I could use in a test case? The names can be mangled for privacy's sake. I'd just like a few canonical examples of IRC lines that use non-RFC formats.

**Comment by glguy** [comment]
I've been quoting from

https://tools.ietf.org/html/rfc2812

I'll have to put together a dump when I get back to this tonight.

**Comment by kallisti-dev** [comment]
Alright so I've made a substantial number of changes to the package. I've added a configuration record as well as 2 modules for RFC1459 and RFC2812 parsing options. The only thing left is to add a "relaxed" parser and run some tests.
